version: "2"
services:
  app:
    build:
      context: "../../"
      dockerfile: "docker/dev/Dockerfile"
    links:
      - "db"
    depends_on:
      - "db"
    environment:
      DJANGO_SETTINGS_MODULE: "todobackend.settings.release"
      MYSQL_HOST: "db"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"
    volumes-from:
      - "webroot"
    command:
      - "uwsgi"
      - "--socket /var/www/todobackend/todobackend.sock"
      - "--chmod-socket=666"
      - "--module todobackend.wsgi"
      - "--masted"
      - "--die-on-term"

  nginx:
    image: "nginx"
    volumes:
      - "./todobackend.conf:/etc/nginx/conf.d/todobackend.conf"
    ports:
      - "8000:8000"
    volumes-from:
      - "webroot"

  webroot:
    build:
      context: "../../"
      dockerfile: "docker/dev/Dockerfile"
    volumes:
      - "/var/www/todobackend"
    entrypoint: "true"

  db:
    image: "mysql:5.6"
    hostname: "db"
    expose: 
      - "3306"
    environment:
      MYSQL_DATABASE: "todobackend"
      MYSQL_USER: "todo"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
